config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }
  
  devise_for :admin, controllers: {
    sessions:       'admin/sessions',
    passwords:      'admin/passwords',
    registrations:  'admin/registrations'
  }
  
  # devise_scope :admin do
  #   get '/admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
  #   post '/admin/sign_in' => 'admin/sessions#create', as: :admin_session
  #   delete '/admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session
  #   get '/admin/password/new' => 'admin/passwords#new', as: :new_admin_password
  #   get '/admin/password/edit' => 'admin/passwords#edit', as: :edit_admin_password
  #   patch '/admin/password' => 'admin/passwords#update', as: :admin_password
  #   put '/admin/password' => 'admin/passwords#update'
  #   post '/admin/cancel' => 'admin/passwords#create'
  #   get '/admin/cancel' => 'admin/registrations#cancel', as: :cancel_admin_registration
  #   get '/admin/sign_up' => 'admin/registrations#new', as: :new_admin_registration
  #   get '/admin/edit' => 'admin/registrations#edit', as: :edit_admin_registration
  #   patch '/admin' => 'admin/registrations#update', as: :admin_registration
  #   put '/admin' => 'admin/registrations#update'
  #   delete '/admin' => 'admin/registrations#destroy'
  #   post '/admin' => 'admin/registrations#create'
  #end
  
  
  scope module: :public do
    root :to => 'homes#top'
    get "/homes/about" =>"homes#about"
    resources :items, only:[:show, :index]
    resources :registrations, only:[:new, :create]
    
    get "customer", to: "customers#show"
    get "/customer/edit" => "customers#edit"
    patch "/customer/update" => "customers#update"
    get "/customer/confirm" => "customers#confirm"
    patch "/customer/renew" => "customers#renew"
  
    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete "destroy_all",to: "cart_items#destroy_all"
      end
    end
    post "/orders/confirm", to: "orders#confirm"
    get "/orders/thanks", to: "orders#thanks"
    resources :orders, only:[:new, :create, :index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end
  
  # /admin/~のURLができる
  namespace :admin do
    root :to => 'homes#top'
    # resources :homes, only:[:top]
    post "/items/new" => "items#create"
    resources :items, only:[:new, :index, :show, :edit, :update]
    resources :genres, only:[:create, :index, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:edit, :update]
    resources :order_items, only:[:update]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  # is_activeがtrueならfalseを返すようにしている
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).reverse_order
  end
  
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer =Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
  if @customer.save
    redirect_to admin_customer_path(@customer)
  else
    render edit_admin_customer_path(@customer)
  end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h4><%= @customer.last_name %><%= @customer.first_name %>
  <%#= @customer.order.name %>さんの会員情報編集</h4>
 
<div class="customer-form">
<%= form_with model:@customer, url: admin_customer_path(@customer), local:true do |f| %>
  <div class="field">
    <%= f.label :会員ID,"会員ID" %>
    <%= @customer.id %>
  </div>
  
  <div class="field">
    <%= f.label :氏名 %>
    <%= f.text_field :last_name, autofocus: true %>
    <%= f.text_field :first_name %>
  </div>
  
  <div class="field">
    <%= f.label :フリガナ %>
    <%= f.text_field :last_name_kana %>
    <%= f.text_field :first_name_kana %>
  </div>

  <div class="field">
    <%= f.label :郵便番号 %>
    <%= f.text_field :postal_code %>
  </div>
  
  <div class="field">
    <%= f.label :住所 %>
    <%= f.text_field :address %>
  </div>
  
  <div class="field">
    <%= f.label :電話番号 %>
    <%= f.text_field :telephone_number %>
  </div>

  <div class="field">
    <%= f.label :メールアドレス %>
    <%= f.email_field :email, autocomplete: "email" %>
  </div>
  
  <div class="field">
    <%= f.label :会員ステータス %>
    <%= f.radio_button :is_active, true, checked: true %>
    <%= f.label :is_active, '有効', value: true %>
    
    <%= f.radio_button :is_active, :false %>
    <%= f.label :is_active, '退会', value: false %>
  </div>
  
  
  <div class="actions">
    <%= f.submit "変更を保存", class: 'btn btn-success' %>
  </div>
<% end %>
</div> 

app/views/admin/customers/index.html.erb
<h4>会員一覧</h4>

<div class="customer-form">
  
<table>
  <thead>
    <tr>
      <th width="15%">会員ID</th>
      <th width="20%">氏名</th>
      <th width="40%">メールアドレス</th>
      <th width="25%">ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td>
        <%= link_to(admin_customer_path(customer)) do %>
          <%= customer.last_name %>
          <%= customer.first_name %>
        <% end %>
      </td>
      <td><%= customer.email %></td>
      <td>
        <% if customer.is_active == true %>
        <p>有効</p>
        <% else %>
        <p>退会</p>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
  <h4>
    <%= @customer.last_name %>
    <%= @customer.first_name %>さんの会員詳細
  </h4>

　<div class="customer-form">
      <div class="customer">
        <span>会員ID</span>
        <%= @customer.id %>
      </div>
      
      <div class="customer">
        <span>氏名</span>
        <%= @customer.last_name %>
        <%= @customer.first_name %>
      </div>
      
      <div class="customer">
        <span>フリガナ</span>
        <%= @customer.last_name_kana %>
        <%= @customer.first_name_kana %>
      </div>
      
      <div class="customer">
        <span>郵便番号</span>
        <%= @customer.postal_code %>
      </div>
      
      <div class="customer">
        <span>住所</span>
        <%= @customer.address %>
      </div>
      
      <div class="customer">
        <span>電話番号</span>
        <%= @customer.telephone_number %>
      </div>
      
      <div class="customer">
        <span>メールアドレス</span>
        <%= @customer.email %>
      </div>
      
      <div class="customer">
        <span>会員ステータス</span>
        <% if @customer.is_active == true %>
        <p>有効</p>
        <% else %>
        <p>退会</p>
        <% end %>
      </div>
    <div class="buttons">
      <div class="edit-botton">
        <%= button_to "編集する", {controller: 'customers', action: 'edit'}, {method: :get, class: 'btn btn-success'} %>
      </div>
      <div class="index-botton">
        <%= link_to "注文履歴一覧を見る", edit_admin_order_path(@customer), class: 'btn btn-primary' %>
      </div>
    </div>
　</div>