config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }
  
  devise_for :admin, controllers: {
    sessions:       'admin/sessions',
    passwords:      'admin/passwords',
    registrations:  'admin/registrations'
  }
  
  # devise_scope :admin do
  #   get '/admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
  #   post '/admin/sign_in' => 'admin/sessions#create', as: :admin_session
  #   delete '/admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session
  #   get '/admin/password/new' => 'admin/passwords#new', as: :new_admin_password
  #   get '/admin/password/edit' => 'admin/passwords#edit', as: :edit_admin_password
  #   patch '/admin/password' => 'admin/passwords#update', as: :admin_password
  #   put '/admin/password' => 'admin/passwords#update'
  #   post '/admin/cancel' => 'admin/passwords#create'
  #   get '/admin/cancel' => 'admin/registrations#cancel', as: :cancel_admin_registration
  #   get '/admin/sign_up' => 'admin/registrations#new', as: :new_admin_registration
  #   get '/admin/edit' => 'admin/registrations#edit', as: :edit_admin_registration
  #   patch '/admin' => 'admin/registrations#update', as: :admin_registration
  #   put '/admin' => 'admin/registrations#update'
  #   delete '/admin' => 'admin/registrations#destroy'
  #   post '/admin' => 'admin/registrations#create'
  #end
  
  
  scope module: :public do
    root :to => 'homes#top'
    get "/homes/about" =>"homes#about"
    resources :items, only:[:show, :index]
    resources :registrations, only:[:new, :create]
    
    get "customer", to: "customers#show"
    get "/customer/edit" => "customers#edit"
    patch "/customer/update" => "customers#update"
    get "/customer/confirm" => "customers#confirm"
    patch "/customer/renew" => "customers#renew"
  
    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete "destroy_all",to: "cart_items#destroy_all"
      end
    end
    post "/orders/confirm", to: "orders#confirm"
    get "/orders/thanks", to: "orders#thanks"
    resources :orders, only:[:new, :create, :index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end
  
  # /admin/~のURLができる
  namespace :admin do
    root :to => 'homes#top'
    # resources :homes, only:[:top]
    post "/items/new" => "items#create"
    resources :items, only:[:new, :index, :show, :edit, :update]
    resources :genres, only:[:create, :index, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:edit, :update]
    resources :order_items, only:[:update]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1}
  enum order_status: { wait: 0, confirmed: 1, making: 2, preparation: 3, sent: 4}
  has_many :order_items, dependent: :destroy
  belongs_to :customer
  

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def edit
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total = 0
      @order_items.each do |order_item|
        @total += order_item.subtotal #小計(税込)
      end
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to edit_admin_order_path(@order)
  end
  
  private
  def order_params
    params.require(:order).permit(:customer_id, :name, :order_status)
  end
  
  def order_item_params
    params.require(:order_item).permit(:price, :amount, :making_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/edit.html.erb
<h4>注文履歴詳細</h4>

  <div class="order">
    <span>購入者</span>
    <%= link_to(admin_customer_path(@order.customer_id)) do %>
    <%= @order.name %>
    <% end %>
  </div>
  
  <div class="order">
    <span>注文日</span>
    <%= @order.created_at %>
  </div>
  
  <div class="customer">
    <span>配送先</span>
  〒<%= @order.postal_code %>
    <%= @order.address %>
    <%= @order.name %>
  </div>
  
  <div class="customer">
    <span>支払方法</span>
      <% if @order.payment_method == "credit_card" %>
       <p>クレジットカード</p>
       <% elsif @order.payment_method == "transfer" %>
       <p>銀行振込</p>
       <% end %>
  </div>
  
  <div class="customer">
    <span>注文ステータス</span>
    
      <%= form_with model: @order, url:admin_order_path(@order), local:true do |f| %>
        <%= f.select :order_status, [['入金待ち',:wait], ['確認',:confirmed], ['制作中',:making], ['準備中',:preparation], ['発送済み',:sent]] %>
        <%= f.submit '更新', class: 'btn btn-primary' %>
      <% end %>
  </div>
  
  <table>
  <thead>
    <tr>
      <th>商品名</th>
      <th>単価(税込)</th>
      <th>数量</th>
      <th>小計</th>
      <th>制作ステータス</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @order_items.each do |order_item| %>
    <tr>
      <td><%= order_item.item.name %></td>
      <td><%= (order_item.item.price*1.1).to_i %></td>
      <td><%= order_item.amount %></td>
      <td><%= order_item.subtotal %></td>
      <td></td>
    </tr>
    <% end %>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th>商品合計</th>
      <th>送料</th>
      <th>請求金額合計</th>
    </tr>
    
    
    <tr>
      <td><%= @total %></td>
      <td>800円</td>
      <td><%= @total+800 %></td>
    </tr>
   
  </thead>
</table>
  
  
  
  