config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }
  
  devise_for :admin, controllers: {
    sessions:       'admin/sessions',
    passwords:      'admin/passwords',
    registrations:  'admin/registrations'
  }
  
  # devise_scope :admin do
  #   get '/admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
  #   post '/admin/sign_in' => 'admin/sessions#create', as: :admin_session
  #   delete '/admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session
  #   get '/admin/password/new' => 'admin/passwords#new', as: :new_admin_password
  #   get '/admin/password/edit' => 'admin/passwords#edit', as: :edit_admin_password
  #   patch '/admin/password' => 'admin/passwords#update', as: :admin_password
  #   put '/admin/password' => 'admin/passwords#update'
  #   post '/admin/cancel' => 'admin/passwords#create'
  #   get '/admin/cancel' => 'admin/registrations#cancel', as: :cancel_admin_registration
  #   get '/admin/sign_up' => 'admin/registrations#new', as: :new_admin_registration
  #   get '/admin/edit' => 'admin/registrations#edit', as: :edit_admin_registration
  #   patch '/admin' => 'admin/registrations#update', as: :admin_registration
  #   put '/admin' => 'admin/registrations#update'
  #   delete '/admin' => 'admin/registrations#destroy'
  #   post '/admin' => 'admin/registrations#create'
  #end
  
  
  scope module: :public do
    root :to => 'homes#top'
    get "/homes/about" =>"homes#about"
    resources :items, only:[:show, :index]
    resources :registrations, only:[:new, :create]
    
    get "customer", to: "customers#show"
    get "/customer/edit" => "customers#edit"
    patch "/customer/update" => "customers#update"
    get "/customer/confirm" => "customers#confirm"
    patch "/customer/renew" => "customers#renew"
  
    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete "destroy_all",to: "cart_items#destroy_all"
      end
    end
    post "/orders/confirm", to: "orders#confirm"
    get "/orders/thanks", to: "orders#thanks"
    resources :orders, only:[:new, :create, :index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
  end
  
  # /admin/~のURLができる
  namespace :admin do
    root :to => 'homes#top'
    # resources :homes, only:[:top]
    post "/items/new" => "items#create"
    resources :items, only:[:new, :index, :show, :edit, :update]
    resources :genres, only:[:create, :index, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:edit, :update]
    resources :order_items, only:[:update]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
 
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  # is_activeがtrueならfalseを返すようにしている
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1}
  enum order_status: { wait: 0, confirmed: 1, making: 2, preparation: 3, sent: 4}
  has_many :order_items, dependent: :destroy
  belongs_to :customer
  

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
   
  def subtotal
    item.with_tax_price * amount
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 def top
  @orders = Order.page(params[:page]).reverse_order
 end
 
 
private
def order_params
 params.require(:order).permit(:name, :order_status)
end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
  if @item.save
    redirect_to admin_item_path(@item)#@item.idと同じ
  else
    render new_admin_item_path
  end
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def index
    @items = Item.page(params[:page]).reverse_order
  end
  
  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
  if @item.save
    redirect_to admin_item_path(@item)
  else
    render edit_admin_item_path(@item)
  end
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #applicationControllerを継承するコントローラー内のすべてのアクションが実行される前に、before_actionが実行される。
  #configure_permitted_parametersはストロングパラメーターを反映させる
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  def after_sign_in_path_for(resource)
    case resource
    when Admin #Adminモデル
      admin_root_path #遷移先のパス
    when Customer
      root_path              
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    # case resource
    if resource_or_scope == :admin
    # when Admin #Adminモデル
      new_admin_session_path #遷移先のパス
    # when Customer
    else
      root_path              
    end
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/91078cb5ad.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-light navbar-expand-lg">
        <div class="container">
          
          <div class="navbar-brand">
            <%= link_to "LOGO", root_path, class: "link-logo" %>
          </div>
          
          <!--<% if customer_signed_in? %>-->
          <!--  ようこそ、<%= current_customer.last_name %>さん！-->
          <!--<% end %>-->
          
  
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li class="nav-item active"><%= link_to "商品一覧", admin_items_path, class: "link" %></li>
              <li class="nav-item active"><%= link_to "会員一覧", admin_customers_path, class: "link" %></li>
              <li class="nav-item active"><%= link_to "注文履歴一覧", admin_root_path, class: "link" %></li>
              <li class="nav-item active"><%= link_to "ジャンル一覧", admin_genres_path, class: "link" %></li>
              <li class="nav-item active"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "link" %></li>
            <% elsif customer_signed_in? %>
              <li class="nav-item active"><%= link_to 'マイページ', customer_path(current_customer), class: "link" %></li>
              <li class="nav-item active"><%= link_to "商品一覧", items_path, class: "link"  %></li>
              <li class="nav-item active"><%= link_to "カート", cart_items_path, class: "link"  %></li>
              <li class="nav-item active"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "link" %></li>
             <% else %>
              <li class="nav-item active"><%= link_to "About", homes_about_path, class: "link" %></li>
              <li class="nav-item active"><%= link_to "商品一覧", items_path, class: "link"  %></li>
              <li class="nav-item active"><%= link_to "新規登録", new_customer_registration_path, class: "link"  %></li>
              <li class="nav-item active"><%= link_to "ログイン", new_customer_session_path, class: "link"  %></li>
            <% end %>
          </ul>
          </div>
        </div>
      </nav>
      <!--font awesome読み込む-->
      <div class="text-right">
        <input type="text" placeholder="Search">
        <button type="submit"><i class="fa fa-search"></i></button>
      </div>
      
      </div>
      
    </header>
    
    <main>
      <%= yield %>
    </main>
  </body>
</html>